name: Ensure API Peer Dependency

on:
  workflow_dispatch:

jobs:
  peer-api-check:
    runs-on: ubuntu-latest
    container:
      image: node:18
    steps:
      - name: Configure npm time machine registry
        run: npm config set registry https://:2023-03-20T16%3A10%3A31.107000Z@time-machines-npm.sealsecurity.io/
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install lerna
        run: npm install -g lerna

      - name: Install semver
        run: npm install semver

      - name: Check API dependency semantics
        working-directory: packages
        run: lerna run peer-api-check
    timeout-minutes: 40
